version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rhorizon
    ports:
      - "5432:5432"
